"""Add title and image_url to Post

Revision ID: 30fec8611d25
Revises: f7b6e9429916
Create Date: 2025-04-18 22:36:16.155187

"""

# revision identifiers, used by Alembic.
revision = '30fec8611d25'
down_revision = 'f7b6e9429916'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.String(length=256), nullable=True))
    op.add_column('posts', sa.Column('title', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###
